name: JMeter Performance Test

on:
  workflow_dispatch:

jobs:
  jmeter-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      # Set timestamp for unique file naming
      - name: Set timestamp
        run: echo "TIMESTAMP=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      # Create reports directory with timestamp
      - name: Create reports directory
        run: mkdir -p reports_${{ env.TIMESTAMP }}

      # Run JMeter Test with HTML report generation, storing reports in the timestamped directory
      - name: JMeter Test
        uses: QAInsights/PerfAction@v5.6.2
        with:
          test-plan-path: ./jmeterTests/PerformanceTests/FlightBookingDemoForNonGUIModeExecution.jmx
          args: "-n -t https://github.com/umohanbabu107/jmeterTests/PerformanceTests/FlightBookingDemoForNonGUIModeExecution.jmx -l ./result_${{ env.TIMESTAMP }}.jtl -e -o ./reports_${{ env.TIMESTAMP }}/html/"

      # Debugging: List files in the current directory
      - name: List files
        run: ls -la

      # Upload raw results (result.jtl) with timestamp
      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results-${{ env.TIMESTAMP }}
          path: ./result_${{ env.TIMESTAMP }}.jtl
          if-no-files-found: error

      # Upload HTML reports with timestamp
      - name: Upload HTML Reports
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-html-reports-${{ env.TIMESTAMP }}
          path: reports_${{ env.TIMESTAMP }}
          if-no-files-found: error
